"""1st migration: adding all fields from data"


Revision ID: 8f30e0c5f326
Revises: 
Create Date: 2024-05-30 16:13:36.470164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f30e0c5f326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('match_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('home_team', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('away_team', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('result', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('result')
        batch_op.drop_column('away_team')
        batch_op.drop_column('home_team')
        batch_op.drop_column('description')
        batch_op.drop_column('match_id')
        batch_op.drop_column('season')

    # ### end Alembic commands ###
